# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Serial_MainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Serial_MainWindow(object):
    def setupUi(self, Serial_MainWindow):
        Serial_MainWindow.setObjectName("Serial_MainWindow")
        Serial_MainWindow.resize(800, 600)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Serial_MainWindow.sizePolicy().hasHeightForWidth())
        Serial_MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(Serial_MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.centralwidget.sizePolicy().hasHeightForWidth())
        self.centralwidget.setSizePolicy(sizePolicy)
        self.centralwidget.setObjectName("centralwidget")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(240, 220, 97, 29))
        self.pushButton.setObjectName("pushButton")
        Serial_MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Serial_MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 27))
        self.menubar.setObjectName("menubar")
        Serial_MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Serial_MainWindow)
        self.statusbar.setObjectName("statusbar")
        Serial_MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(Serial_MainWindow)
        QtCore.QMetaObject.connectSlotsByName(Serial_MainWindow)

    def retranslateUi(self, Serial_MainWindow):
        _translate = QtCore.QCoreApplication.translate
        Serial_MainWindow.setWindowTitle(_translate("Serial_MainWindow", "MainWindow"))
        self.pushButton.setText(_translate("Serial_MainWindow", "PushButton"))
